# Configuration parameters to download experimental data and/or edit its format,
# used by the script get_expdata.py.
#
# You can specify one or more blocks for HEPData, PHENIX, or EditData or any combination,
# and they will all be processed according to their appropriate scripts, steered by get_expdata.py.

filepath: &filepath "input/MATTERLBT-QM-2022-Hadron-Jet-RAA/"

## Development area

# This block will stop the script immediately so we don't unnecessarily hit hepdata
# Uncomment when needed
#hepdata_break:
#  data_url: [""]
## End development area

#########################
### Hadron RAA
#########################

## PHENIX Hadron RAA
# We take it from hepdata instead of phenix because the phenix page was down
# Note: Avoid "PHENIX" in the name so that the get_phenix script doesn't try to pick this up.
## Checked: RJE
hepdata_phx_hadronRAA:
  filepath: *filepath
  data_vrs: 'Version 1.0'
  data_str: 'Data'
  data_url: [
    "https://www.hepdata.net/download/table/ins1127262/Figure%2011/2/yaml",
    "https://www.hepdata.net/download/table/ins1127262/Figure%2011/2/yaml",
    "https://www.hepdata.net/download/table/ins1127262/Figure%2011/2/yaml",
    "https://www.hepdata.net/download/table/ins1127262/Figure%2011/2/yaml",
    "https://www.hepdata.net/download/table/ins1127262/Figure%2011/2/yaml",
    "https://www.hepdata.net/download/table/ins1127262/Figure%2011/2/yaml",
  ]
  data_doi: ['https://doi.org/10.1103/PhysRevC.87.034911','https://doi.org/10.1103/PhysRevC.87.034911','https://doi.org/10.1103/PhysRevC.87.034911','https://doi.org/10.1103/PhysRevC.87.034911','https://doi.org/10.1103/PhysRevC.87.034911','https://doi.org/10.1103/PhysRevC.87.034911', ]
  data_fig: ['figure 11','figure 11','figure 11','figure 11','figure 11','figure 11',]
  data_exp: ['PHENIX','PHENIX','PHENIX','PHENIX','PHENIX','PHENIX']
  data_sys: ['AuAu200','AuAu200','AuAu200','AuAu200','AuAu200','AuAu200']
  data_qualifiers: [
    # NOTE: The name is wrong in the file...
    {name: '$p_T$', value: '$0-5\%$ centrality'},
    {name: '$p_T$', value: '$0-10\%$ centrality'},
    {name: '$p_T$', value: '$10-20\%$ centrality'},
    {name: '$p_T$', value: '$20-30\%$ centrality'},
    {name: '$p_T$', value: '$30-40\%$ centrality'},
    {name: '$p_T$', value: '$40-50\%$ centrality'},
  ]
  data_meas: ['RAACharged','RAACharged','RAACharged','RAACharged', "RAACharged", "RAACharged"]
  data_cent: ['0-5', '0-10', '10-20', '20-30', '30-40', '40-50']
  data_year: ['2013','2013','2013','2013', "2013", "2013"]

## CMS and ATLAS hadron RAA
hepdata_hadronRAA_CMS_ATLAS:
  filepath: *filepath
  data_vrs: 'Version 1.0'
  data_str: 'Data'
  data_url: ['https://www.hepdata.net/download/table/ins1496050/Table14/yaml', 'https://www.hepdata.net/download/table/ins1496050/Table11/yaml', 'https://www.hepdata.net/download/table/ins1360290/Table27/1/yaml', 'https://www.hepdata.net/download/table/ins1360290/Table29/1/yaml']
  data_doi: ['http://dx.doi.org/10.1007/JHEP04(2017)039', 'http://dx.doi.org/10.1007/JHEP04(2017)039', 'http://dx.doi.org/10.1007/JHEP09(2015)050', 'http://dx.doi.org/10.1007/JHEP09(2015)050']
  data_fig: ['figure 4a','figure 4b','figure 13','figure 13']
  data_exp: ['CMS','CMS','ATLAS','ATLAS']
  data_sys: ['PbPb5020','PbPb5020','PbPb2760','PbPb2760']
  data_meas: ['RAACharged','RAACharged','RAACharged','RAACharged']
  data_cent: ['0-10','30-50','0-5','30-50']
  data_year: ['2017','2017','2015','2015']

#########################
### Jet RAA
#########################

## 200 GeV STAR
# NOTE: Includes the "biased" region!
## Checked: RJE
hepdata_STAR_JetRAA_200:
  filepath: *filepath
  data_vrs: "Version 1.0"
  data_str: "Data"
  data_url: ["https://www.hepdata.net/download/table/ins1798665/Table%2010/1/yaml", "https://www.hepdata.net/download/table/ins1798665/Table%2010/1/yaml", "https://www.hepdata.net/download/table/ins1798665/Table%2010/1/yaml"]
  data_doi: ["https://doi.org/10.1103/PhysRevC.102.054913", "https://doi.org/10.1103/PhysRevC.102.054913", "https://doi.org/10.1103/PhysRevC.102.054913"]
  data_fig: ['figure 17, bottom', 'figure 17, bottom', 'figure 17, bottom']
  data_exp: ['STAR', 'STAR', 'STAR']
  data_sys: ['AuAu200', 'AuAu200', 'AuAu200']
  data_qualifiers: [
    {name: '$p_{T,jet}^{ch}$ $(\mathrm{GeV}/c)$', value: '$R=0.2$'},
    {name: '$p_{T,jet}^{ch}$ $(\mathrm{GeV}/c)$', value: '$R=0.3$'},
    {name: '$p_{T,jet}^{ch}$ $(\mathrm{GeV}/c)$', value: '$R=0.4$'}
  ]
  data_meas: ['JetRAAR02', 'JetRAAR03', 'JetRAAR04']
  data_cent: ['0-10', '0-10', '0-10']
  data_year: ['2011', '2011', '2011']

## 2.76 TeV ALICE
## Checked: RJE
hepdata_ALICE_JetRAA_2760:
  filepath: *filepath
  data_vrs: "Version 1.0"
  data_str: "Data"
  data_url: ["https://www.hepdata.net/download/table/ins1343112/Table%206/1/yaml", "https://www.hepdata.net/download/table/ins1343112/Table%207/1/yaml"]
  data_doi: ["https://doi.org/10.1016/j.physletb.2015.04.039", "https://doi.org/10.1016/j.physletb.2015.04.039"]
  data_fig: ['figure 5, left', 'figure 5, right']
  data_exp: ['ALICE', 'ALICE']
  data_sys: ['PbPb2760', 'PbPb2760']
  data_meas: ['JetRAAR02', 'JetRAAR02']
  data_cent: ['0-10', '10-30']
  data_year: ['2011', '2011']

## 2.76 TeV ATLAS
## Checked: RJE
hepdata_ATLAS_JetRAA_2760:
  filepath: *filepath
  data_vrs: "Version 1.0"
  data_str: "Data"
  data_url: [
    "https://www.hepdata.net/download/table/ins1326911/Table%2027/1/yaml",
    "https://www.hepdata.net/download/table/ins1326911/Table%2028/1/yaml",
    "https://www.hepdata.net/download/table/ins1326911/Table%2029/1/yaml",
    "https://www.hepdata.net/download/table/ins1326911/Table%2030/1/yaml",
    "https://www.hepdata.net/download/table/ins1326911/Table%2031/1/yaml",
  ]
  data_doi: [
    "https://doi.org/10.1103/PhysRevLett.114.072302",
    "https://doi.org/10.1103/PhysRevLett.114.072302",
    "https://doi.org/10.1103/PhysRevLett.114.072302",
    "https://doi.org/10.1103/PhysRevLett.114.072302",
    "https://doi.org/10.1103/PhysRevLett.114.072302",
  ]
  data_fig: ["Figure 3, top", "Figure 3, top", "Figure 3, top", "Figure 3, top", "Figure 3, top"]
  data_exp: ['ATLAS', 'ATLAS', 'ATLAS', 'ATLAS', 'ATLAS']
  data_sys: ['PbPb2760', 'PbPb2760', 'PbPb2760', 'PbPb2760', 'PbPb2760']
  data_meas: ['JetRAAR04', 'JetRAAR04', 'JetRAAR04', 'JetRAAR04', 'JetRAAR04']
  data_cent: ['0-10', '10-20', '20-30', "30-40", "40-50"]
  data_year: ['2011', '2011', "2011", "2011", "2011"]

## 2.76 TeV CMS
## Checked: RJE
hepdata_CMS_JetRAA_2760:
  filepath: *filepath
  data_vrs: "Version 1.0"
  data_str: "Data"
  data_url: [
    # 0-5%
    "https://www.hepdata.net/download/table/ins1487278/Table%208a/1/yaml", "https://www.hepdata.net/download/table/ins1487278/Table%208a/1/yaml", "https://www.hepdata.net/download/table/ins1487278/Table%208a/1/yaml",
    # 5-10%
    "https://www.hepdata.net/download/table/ins1487278/Table%208b/1/yaml", "https://www.hepdata.net/download/table/ins1487278/Table%208b/1/yaml", "https://www.hepdata.net/download/table/ins1487278/Table%208b/1/yaml",
    # 10-30%
    "https://www.hepdata.net/download/table/ins1487278/Table%208c/1/yaml", "https://www.hepdata.net/download/table/ins1487278/Table%208c/1/yaml", "https://www.hepdata.net/download/table/ins1487278/Table%208c/1/yaml",
    # 30-50%
    "https://www.hepdata.net/download/table/ins1487278/Table%208d/1/yaml", "https://www.hepdata.net/download/table/ins1487278/Table%208d/1/yaml", "https://www.hepdata.net/download/table/ins1487278/Table%208d/1/yaml",
  ]
  data_doi: [
    "https://doi.org/10.1103/PhysRevC.96.015202", "https://doi.org/10.1103/PhysRevC.96.015202", "https://doi.org/10.1103/PhysRevC.96.015202",
    "https://doi.org/10.1103/PhysRevC.96.015202", "https://doi.org/10.1103/PhysRevC.96.015202", "https://doi.org/10.1103/PhysRevC.96.015202",
    "https://doi.org/10.1103/PhysRevC.96.015202", "https://doi.org/10.1103/PhysRevC.96.015202", "https://doi.org/10.1103/PhysRevC.96.015202",
    "https://doi.org/10.1103/PhysRevC.96.015202", "https://doi.org/10.1103/PhysRevC.96.015202", "https://doi.org/10.1103/PhysRevC.96.015202",
  ]
  data_fig: [
    'Figure 8-a', 'Figure 8-a', "Figure 8-a",
    'Figure 8-b', 'Figure 8-b', "Figure 8-b",
    'Figure 8-c', 'Figure 8-c', "Figure 8-c",
    'Figure 8-d', 'Figure 8-d', "Figure 8-d",
  ]
  data_exp: [
    'CMS', 'CMS', "CMS",
    'CMS', 'CMS', "CMS",
    'CMS', 'CMS', "CMS",
    'CMS', 'CMS', "CMS",
  ]
  data_sys: [
    'PbPb2760', 'PbPb2760', "PbPb2760",
    'PbPb2760', 'PbPb2760', "PbPb2760",
    'PbPb2760', 'PbPb2760', "PbPb2760",
    'PbPb2760', 'PbPb2760', "PbPb2760",
  ]
  data_qualifiers: [
    # 0-5%
    {name: anti-k$_T$ R, value: 0.2}, {name: anti-k$_T$ R, value: 0.3}, {name: anti-k$_T$ R, value: 0.4},
    # 5-10%
    {name: anti-k$_T$ R, value: 0.2}, {name: anti-k$_T$ R, value: 0.3}, {name: anti-k$_T$ R, value: 0.4},
    # 10-30%
    {name: anti-k$_T$ R, value: 0.2}, {name: anti-k$_T$ R, value: 0.3}, {name: anti-k$_T$ R, value: 0.4},
    # 30-50%
    {name: anti-k$_T$ R, value: 0.2}, {name: anti-k$_T$ R, value: 0.3}, {name: anti-k$_T$ R, value: 0.4},
  ]
  data_meas: [
    # 0-5%
    'JetRAAR02', 'JetRAAR03', 'JetRAAR04',
    # 5-10%
    'JetRAAR02', 'JetRAAR03', 'JetRAAR04',
    # 10-30%
    'JetRAAR02', 'JetRAAR03', 'JetRAAR04',
    # 30-50%
    'JetRAAR02', 'JetRAAR03', 'JetRAAR04',
  ]
  data_cent: [
    "0-5", "0-5", "0-5",
    "5-10", "5-10", "5-10",
    "10-30", "10-30", "10-30",
    "30-50", "30-50", "30-50",
  ]
  data_year: [
    '2011', '2011', "2011",
    '2011', '2011', "2011",
    '2011', '2011', "2011",
    '2011', '2011', "2011",
  ]

## 5 TeV ALICE
## Checked: RJE
hepdata_ALICE_JetRAA_5020:
  filepath: *filepath
  data_vrs: "Version 1.0"
  data_str: "Data"
  data_url: ["https://www.hepdata.net/download/table/ins1755387/Table%2030/1/yaml", "https://www.hepdata.net/download/table/ins1755387/Table%2031/1/yaml"]
  data_doi: ['https://doi.org/10.1103/PhysRevC.101.034911', 'https://doi.org/10.1103/PhysRevC.101.034911']
  data_fig: ['figure 6a', 'figure 6b']
  data_exp: ['ALICE', 'ALICE']
  data_sys: ['PbPb5020', 'PbPb5020']
  data_meas: ['JetRAAR02', 'JetRAAR04']
  data_cent: ['0-10', '0-10']
  data_year: ['2015', '2015']

## 5 TeV ATLAS
## Checked: RJE
hepdata_ATLAS_JetRAA_5020:
  filepath: *filepath
  data_vrs: "Version 1.0"
  data_str: "Data"
  data_url: ["https://www.hepdata.net/download/table/ins1673184/Table%2019/1/yaml",
             "https://www.hepdata.net/download/table/ins1673184/Table%2020/1/yaml",
             "https://www.hepdata.net/download/table/ins1673184/Table%2021/1/yaml",
             "https://www.hepdata.net/download/table/ins1673184/Table%2022/1/yaml",
             "https://www.hepdata.net/download/table/ins1673184/Table%2023/1/yaml"]
  data_doi: ["https://doi.org/10.1016/j.physletb.2018.10.076", "https://doi.org/10.1016/j.physletb.2018.10.076", "https://doi.org/10.1016/j.physletb.2018.10.076", "https://doi.org/10.1016/j.physletb.2018.10.076", "https://doi.org/10.1016/j.physletb.2018.10.076"]
  data_fig: ['figure 4', 'figure 4', 'figure 4', 'figure 4', "figure 4"]
  data_exp: ['ATLAS', "ATLAS", 'ATLAS', "ATLAS", 'ATLAS']
  data_sys: ['PbPb5020', 'PbPb5020', 'PbPb5020', 'PbPb5020', 'PbPb5020']
  data_meas: ['JetRAAR04', 'JetRAAR04', 'JetRAAR04', 'JetRAAR04', 'JetRAAR04']
  data_cent: ['0-10', '10-20', "20-30", "30-40", "40-50"]
  data_year: ['2015', '2015', '2015', '2015', '2015']

## 5 TeV CMS
## Checked: RJE
hepdata_CMS_JetRAA_5020:
  filepath: *filepath
  data_vrs: "Version 1.0"
  data_str: "Data"
  data_url: [
    # R02
    "https://www.hepdata.net/download/table/ins1848440/Figure%207-1/1/yaml", "https://www.hepdata.net/download/table/ins1848440/Figure%207-1/1/yaml", "https://www.hepdata.net/download/table/ins1848440/Figure%207-1/1/yaml",
    # R03
    "https://www.hepdata.net/download/table/ins1848440/Figure%207-2/1/yaml", "https://www.hepdata.net/download/table/ins1848440/Figure%207-2/1/yaml", "https://www.hepdata.net/download/table/ins1848440/Figure%207-2/1/yaml",
    # R04
    "https://www.hepdata.net/download/table/ins1848440/Figure%207-3/1/yaml", "https://www.hepdata.net/download/table/ins1848440/Figure%207-3/1/yaml", "https://www.hepdata.net/download/table/ins1848440/Figure%207-3/1/yaml",
    # R06
    "https://www.hepdata.net/download/table/ins1848440/Figure%207-4/1/yaml", "https://www.hepdata.net/download/table/ins1848440/Figure%207-4/1/yaml", "https://www.hepdata.net/download/table/ins1848440/Figure%207-4/1/yaml",
    # R08
    "https://www.hepdata.net/download/table/ins1848440/Figure%207-5/1/yaml", "https://www.hepdata.net/download/table/ins1848440/Figure%207-5/1/yaml", "https://www.hepdata.net/download/table/ins1848440/Figure%207-5/1/yaml",
    # R10
    "https://www.hepdata.net/download/table/ins1848440/Figure%207-6/1/yaml", "https://www.hepdata.net/download/table/ins1848440/Figure%207-6/1/yaml", "https://www.hepdata.net/download/table/ins1848440/Figure%207-6/1/yaml",
  ]
  data_doi: [
    # R02
    "https://doi.org/10.1007/JHEP05(2021)284", "https://doi.org/10.1007/JHEP05(2021)284", "https://doi.org/10.1007/JHEP05(2021)284",
    # R03
    "https://doi.org/10.1007/JHEP05(2021)284", "https://doi.org/10.1007/JHEP05(2021)284", "https://doi.org/10.1007/JHEP05(2021)284",
    # R04
    "https://doi.org/10.1007/JHEP05(2021)284", "https://doi.org/10.1007/JHEP05(2021)284", "https://doi.org/10.1007/JHEP05(2021)284",
    # R06
    "https://doi.org/10.1007/JHEP05(2021)284", "https://doi.org/10.1007/JHEP05(2021)284", "https://doi.org/10.1007/JHEP05(2021)284",
    # R08
    "https://doi.org/10.1007/JHEP05(2021)284", "https://doi.org/10.1007/JHEP05(2021)284", "https://doi.org/10.1007/JHEP05(2021)284",
    # R10
    "https://doi.org/10.1007/JHEP05(2021)284", "https://doi.org/10.1007/JHEP05(2021)284", "https://doi.org/10.1007/JHEP05(2021)284",
  ]
  data_fig: [
    # R02
    'figure 7-1', 'figure 7-1', 'figure 7-1',
    # R03
    'figure 7-2', 'figure 7-2', 'figure 7-2',
    # R04
    'figure 7-3', 'figure 7-3', 'figure 7-3',
    # R06
    'figure 7-4', 'figure 7-4', 'figure 7-4',
    # R08
    'figure 7-5', 'figure 7-5', 'figure 7-5',
    # R10
    'figure 7-6', 'figure 7-6', 'figure 7-6',
  ]
  data_exp: [
    # R02
    'CMS', "CMS", "CMS",
    # R03
    'CMS', "CMS", "CMS",
    # R04
    'CMS', "CMS", "CMS",
    # R06
    'CMS', "CMS", "CMS",
    # R08
    'CMS', "CMS", "CMS",
    # R10
    'CMS', "CMS", "CMS",
  ]
  data_sys: [
    # R02
    'PbPb5020', 'PbPb5020', 'PbPb5020',
    # R03
    'PbPb5020', 'PbPb5020', 'PbPb5020',
    # R04
    'PbPb5020', 'PbPb5020', 'PbPb5020',
    # R06
    'PbPb5020', 'PbPb5020', 'PbPb5020',
    # R08
    'PbPb5020', 'PbPb5020', 'PbPb5020',
    # R10
    'PbPb5020', 'PbPb5020', 'PbPb5020',
  ]
  data_qualifiers: [
    # R02
    {name: CENTRALITY, value: 0-10}, {name: CENTRALITY, value: 10-30}, {name: CENTRALITY, value: 30-50},
    # R03
    {name: CENTRALITY, value: 0-10}, {name: CENTRALITY, value: 10-30}, {name: CENTRALITY, value: 30-50},
    # R04
    {name: CENTRALITY, value: 0-10}, {name: CENTRALITY, value: 10-30}, {name: CENTRALITY, value: 30-50},
    # R06
    {name: CENTRALITY, value: 0-10}, {name: CENTRALITY, value: 10-30}, {name: CENTRALITY, value: 30-50},
    # R08
    {name: CENTRALITY, value: 0-10}, {name: CENTRALITY, value: 10-30}, {name: CENTRALITY, value: 30-50},
    # R10
    {name: CENTRALITY, value: 0-10}, {name: CENTRALITY, value: 10-30}, {name: CENTRALITY, value: 30-50},
  ]
  data_meas: [
    # R02
    'JetRAAR02', 'JetRAAR02', 'JetRAAR02',
    # R03
    'JetRAAR03', 'JetRAAR03', 'JetRAAR03',
    # R04
    'JetRAAR04', 'JetRAAR04', 'JetRAAR04',
    # R06
    'JetRAAR06', 'JetRAAR06', 'JetRAAR06',
    # R08
    'JetRAAR08', 'JetRAAR08', 'JetRAAR08',
    # R10
    'JetRAAR10', 'JetRAAR10', 'JetRAAR10',
  ]
  data_cent: [
    # R02
    '0-10', '10-30', "30-50",
    # R03
    '0-10', '10-30', "30-50",
    # R04
    '0-10', '10-30', "30-50",
    # R06
    '0-10', '10-30', "30-50",
    # R08
    '0-10', '10-30', "30-50",
    # R10
    '0-10', '10-30', "30-50",
  ]
  data_year: [
    # R02
    '2015', '2015', '2015',
    # R03
    '2015', '2015', '2015',
    # R04
    '2015', '2015', '2015',
    # R06
    '2015', '2015', '2015',
    # R08
    '2015', '2015', '2015',
    # R10
    '2015', '2015', '2015',
  ]
